#! /bin/bash

# Match by quota

# Flush the tables
iptables -F

# Permit max quota bytes from protocol tcp and port 80 (Routed traffic, we are the router)
# Traffic is generated by a server inside our LAN. This is downloaded traffic
# by Internet clients from our server.

# Edit the values below

PROTOCOL="tcp"
PORT="80"

#1GB
QUOTA1="1000000000"

# This is the outgoing interface
INT="eth0"

# Do not edit below this line
iptables -A FORWARD -o $INT -p $PROTOCOL --sport $PORT -m quota --quota $QUOTA1 -j ACCEPT

iptables -A FORWARD -o $INT -p $PROTOCOL --sport $PORT -j DROP

#------------------------------------------------------------------------

# Permit max 100MB of incoming https traffic from the web site with the address 100.0.0.1

# Edit the values below
HTTPS_SERVER="100.0.0.1"
PROTOCOL="tcp"
PORT="443"

# 100MB
QUOTA2="100000000"

# Do not edit below this line

iptables -A INPUT -s $HTTPS_SERVER -p $PROTOCOL --sport $PORT -m quota --quota $QUOTA2 -j ACCEPT

iptables -A INPUT -p $PROTOCOL --sport $PORT -j DROP